# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registerFrame2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(403, 303)
        Form.setMinimumSize(QtCore.QSize(403, 303))
        Form.setMaximumSize(QtCore.QSize(403, 303))
        Form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(381, 281))
        self.frame.setMaximumSize(QtCore.QSize(381, 281))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                 "font: 75 14pt \"Verdana\";\n"
                                 "color: #eeeeee;\n"
                                 "border-radius: 20px;\n"
                                 "background-color: rgb(82, 5, 123);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 70, 381, 51))
        self.label.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
                                 "font: 75 18pt \"Calibri\";\n"
                                 "font: 75 18pt \"Calibri\";\n"
                                 "color: rgb(170, 0, 255);\n"
                                 "color: rgb(170, 85, 255);\n"
                                 "color: #eeeeee;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(130, 150, 120, 50))
        self.pushButton.setMinimumSize(QtCore.QSize(120, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(120, 50))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
                                      "border: 4px solid #bc6ff1;\n"
                                      "border-radius: 25px;\n"
                                      "font: 75 12pt \"MS Shell Dlg 2\";\n"
                                      "    background-color: rgb(51, 0, 79);\n"
                                      "\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover{\n"
                                      "border: 3px solid #aa55ff;\n"
                                      "background-color: #410062;\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Registeration Successful"))
        self.pushButton.setText(_translate("Form", "Home"))

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_Form()
#     ui.setupUi(MainWindow)
#     MainWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint)
#     MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
#     MainWindow.show()
#     sys.exit(app.exec_())