# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchBatch.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import mysql.connector

mydb = mysql.connector.connect(
    host="127.0.0.1",
    user="local",
    password="",
    database="bitsfinal"
)


class Ui_SearchInBatch(object):
    def setupUi(self, SearchInBatch):
        SearchInBatch.setObjectName("SearchInBatch")
        SearchInBatch.resize(1233, 853)
        SearchInBatch.setStyleSheet("QMainWindow{\n"
                                    "background-color: #212121;\n"
                                    "}\n"
                                    "\n"
                                    "QWidget#batchInfo{\n"
                                    "background-color: #212121;\n"
                                    "border-color: rgb(26, 255, 187);\n"
                                    "}\n"
                                    "QWidget#studentInBatch{\n"
                                    "background-color: #212121;\n"
                                    "}\n"
                                    "\n"
                                    "QTabWidget::pane { /* The tab widget frame */\n"
                                    "border: 2px solid #32e4c0;\n"
                                    "}\n"
                                    "\n"
                                    "QTabWidget::tab-bar {\n"
                                    "left: 5px; /* move to the right by 5px */\n"
                                    "}\n"
                                    "\n"
                                    "QTabWidget::pane {\n"
                                    "    border: 2px solid #0d7377;\n"
                                    "    background: white;\n"
                                    "}\n"
                                    "\n"
                                    "QTabWidget::tab-bar:top {\n"
                                    "    top: 1px;\n"
                                    "}\n"
                                    "\n"
                                    "QTabWidget::tab-bar:bottom {\n"
                                    "    bottom: 1px;\n"
                                    "}\n"
                                    "\n"
                                    "QTabWidget::tab-bar:left {\n"
                                    "    right: 1px;\n"
                                    "}\n"
                                    "\n"
                                    "QTabWidget::tab-bar:right {\n"
                                    "    left: 1px;\n"
                                    "}\n"
                                    "\n"
                                    "QTabBar::tab {\n"
                                    "    border: 1px solid black;\n"
                                    "}\n"
                                    "\n"
                                    "QTabBar::tab:selected {\n"
                                    "    background:#eeeeee;\n"
                                    "color: #0d7377;\n"
                                    "}\n"
                                    "\n"
                                    "QTabBar::tab:selected:hover{\n"
                                    "    background: white;\n"
                                    "}\n"
                                    "\n"
                                    "QTabBar::tab:!selected {\n"
                                    "    background: #0d7377;\n"
                                    "    color: rgb(238, 238, 238);\n"
                                    "}\n"
                                    "\n"
                                    "QTabBar::tab:!selected:hover {\n"
                                    "    background: #32e4c0;\n"
                                    "}\n"
                                    "\n"
                                    "QTabBar::tab:top:!selected {\n"
                                    "    margin-top: 3px;\n"
                                    "}\n"
                                    "\n"
                                    "QTabBar::tab:bottom:!selected {\n"
                                    "    margin-bottom: 3px;\n"
                                    "}\n"
                                    "\n"
                                    "QTabBar::tab:top, QTabBar::tab:bottom {\n"
                                    "    min-width: 8ex;\n"
                                    "    margin-right: -1px;\n"
                                    "    padding: 5px 10px 5px 10px;\n"
                                    "}\n"
                                    "\n"
                                    "QTabBar::tab:top:selected {\n"
                                    "    border-bottom-color: none;\n"
                                    "}\n"
                                    "\n"
                                    "QTabBar::tab:bottom:selected {\n"
                                    "    border-top-color: none;\n"
                                    "}\n"
                                    "\n"
                                    "QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
                                    "QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one {\n"
                                    "    margin-right: 0;\n"
                                    "}\n"
                                    "\n"
                                    "QTabBar::tab:left:!selected {\n"
                                    "    margin-right: 3px;\n"
                                    "}\n"
                                    "\n"
                                    "QTabBar::tab:right:!selected {\n"
                                    "    margin-left: 3px;\n"
                                    "}\n"
                                    "\n"
                                    "QTabBar::tab:left, QTabBar::tab:right {\n"
                                    "    min-height: 8ex;\n"
                                    "    margin-bottom: -1px;\n"
                                    "    padding: 10px 5px 10px 5px;\n"
                                    "}\n"
                                    "\n"
                                    "QTabBar::tab:left:selected {\n"
                                    "    border-left-color: none;\n"
                                    "}\n"
                                    "\n"
                                    "QTabBar::tab:right:selected {\n"
                                    "    border-right-color: none;\n"
                                    "}\n"
                                    "\n"
                                    "QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
                                    "QTabBar::tab:left:only-one, QTabBar::tab:right:only-one {\n"
                                    "    margin-bottom: 0;\n"
                                    "}")
        self.centralwidget = QtWidgets.QWidget(SearchInBatch)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QLineEdit{\n"
                                     "padding-left: 6px;\n"
                                     "padding-right: 6px;\n"
                                     "border: 2px solid #0d7377;\n"
                                     "border-radius: 5px;\n"
                                     "}\n"
                                     "\n"
                                     "QLineEdit:hover{\n"
                                     "border: 3px solid #32e0c4;\n"
                                     "}\n"
                                     "\n"
                                     "QLabel{\n"
                                     "color: #eeeeee;\n"
                                     "}\n"
                                     "\n"
                                     "QLabel#batchInfoLabel{\n"
                                     "color: #32e0c4;\n"
                                     "}\n"
                                     "\n"
                                     "QLabel#studentInBatchLabel{\n"
                                     "color: #32e0c4;\n"
                                     "}\n"
                                     "\n"
                                     "\n"
                                     "\n"
                                     "QPushButton{\n"
                                     "background-color: #212121;\n"
                                     "Color: #eeeeee;\n"
                                     "border-radius: 20px;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton#backButton{\n"
                                     "color: #eeeeee;\n"
                                     "background-color: #212121;\n"
                                     "border: 2px solid #9a0002;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton#backButton:hover{\n"
                                     "border: 3px solid rgb(255, 0, 0);\n"
                                     "background-color: #9a0002;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton#backButton_2{\n"
                                     "color: #eeeeee;\n"
                                     "background-color: #212121;\n"
                                     "border: 2px solid #9a0002;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton#backButton_2:hover{\n"
                                     "border: 3px solid rgb(255, 0, 0);\n"
                                     "background-color: #9a0002;\n"
                                     "}\n"
                                     "\n"
                                     "\n"
                                     "QComboBox{\n"
                                     "border: 2px solid #0d7377;\n"
                                     "border-radius: 5px;\n"
                                     "padding-left: 4px;\n"
                                     "padding-right: 4px;\n"
                                     "}\n"
                                     "\n"
                                     "QComboBox:hover{\n"
                                     "border: 3px solid #32e0c4;\n"
                                     "}\n"
                                     "\n"
                                     "QComboBox QAbstractItemView {\n"
                                     "border: 2px solid #32e0c4;\n"
                                     "selection-background-color: #0d7377;\n"
                                     "}\n"
                                     "")
        self.tabWidget.setObjectName("tabWidget")
        self.batchInfo = QtWidgets.QWidget()
        self.batchInfo.setObjectName("batchInfo")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.batchInfo)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_18 = QtWidgets.QLabel(self.batchInfo)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout.addWidget(self.label_18)
        self.batchInfoLabel = QtWidgets.QLabel(self.batchInfo)
        self.batchInfoLabel.setMinimumSize(QtCore.QSize(500, 70))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.batchInfoLabel.setFont(font)
        self.batchInfoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.batchInfoLabel.setObjectName("batchInfoLabel")
        self.horizontalLayout.addWidget(self.batchInfoLabel)
        self.label_19 = QtWidgets.QLabel(self.batchInfo)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout.addWidget(self.label_19)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_20 = QtWidgets.QLabel(self.batchInfo)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_2.addWidget(self.label_20)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.selectCourseLabel = QtWidgets.QLabel(self.batchInfo)
        self.selectCourseLabel.setMinimumSize(QtCore.QSize(300, 40))
        self.selectCourseLabel.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.selectCourseLabel.setFont(font)
        self.selectCourseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.selectCourseLabel.setObjectName("selectCourseLabel")
        self.verticalLayout.addWidget(self.selectCourseLabel)
        self.courseComboBox = QtWidgets.QComboBox(self.batchInfo)
        self.courseComboBox.setMinimumSize(QtCore.QSize(300, 40))
        self.courseComboBox.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.courseComboBox.setFont(font)
        self.courseComboBox.setObjectName("courseComboBox")
        self.verticalLayout.addWidget(self.courseComboBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.label_21 = QtWidgets.QLabel(self.batchInfo)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_2.addWidget(self.label_21)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_22 = QtWidgets.QLabel(self.batchInfo)
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_3.addWidget(self.label_22)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.selectBatchLabel = QtWidgets.QLabel(self.batchInfo)
        self.selectBatchLabel.setMinimumSize(QtCore.QSize(300, 40))
        self.selectBatchLabel.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.selectBatchLabel.setFont(font)
        self.selectBatchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.selectBatchLabel.setObjectName("selectBatchLabel")
        self.verticalLayout_2.addWidget(self.selectBatchLabel)
        self.batchComboBox = QtWidgets.QComboBox(self.batchInfo)
        self.batchComboBox.setMinimumSize(QtCore.QSize(300, 40))
        self.batchComboBox.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.batchComboBox.setFont(font)
        self.batchComboBox.setObjectName("batchComboBox")
        self.verticalLayout_2.addWidget(self.batchComboBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.label_23 = QtWidgets.QLabel(self.batchInfo)
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_3.addWidget(self.label_23)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_24 = QtWidgets.QLabel(self.batchInfo)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_4.addWidget(self.label_24)
        self.batchTable = QtWidgets.QTableWidget(self.batchInfo)
        self.batchTable.setMinimumSize(QtCore.QSize(620, 0))
        self.batchTable.setMaximumSize(QtCore.QSize(800, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.batchTable.setFont(font)
        self.batchTable.setObjectName("batchTable")
        self.batchTable.setColumnCount(4)
        self.batchTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        item.setFont(font)
        self.batchTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.batchTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.batchTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.batchTable.setHorizontalHeaderItem(3, item)
        self.batchTable.verticalHeader().setVisible(False)
        self.horizontalLayout_4.addWidget(self.batchTable)
        self.label_25 = QtWidgets.QLabel(self.batchInfo)
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_4.addWidget(self.label_25)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_26 = QtWidgets.QLabel(self.batchInfo)
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_5.addWidget(self.label_26)
        self.backButton = QtWidgets.QPushButton(self.batchInfo)
        self.backButton.setMinimumSize(QtCore.QSize(150, 40))
        self.backButton.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backButton.setFont(font)
        self.backButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_5.addWidget(self.backButton)
        self.label_17 = QtWidgets.QLabel(self.batchInfo)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_5.addWidget(self.label_17)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 2, 2)
        self.tabWidget.addTab(self.batchInfo, "")
        self.studentInBatch = QtWidgets.QWidget()
        self.studentInBatch.setObjectName("studentInBatch")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.studentInBatch)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.studentInBatch)
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.studentInBatch)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.studentInBatchLabel = QtWidgets.QLabel(self.studentInBatch)
        self.studentInBatchLabel.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.studentInBatchLabel.setFont(font)
        self.studentInBatchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.studentInBatchLabel.setObjectName("studentInBatchLabel")
        self.horizontalLayout_6.addWidget(self.studentInBatchLabel)
        self.label_3 = QtWidgets.QLabel(self.studentInBatch)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.studentInBatch)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.selectCourseLabel_2 = QtWidgets.QLabel(self.studentInBatch)
        self.selectCourseLabel_2.setMinimumSize(QtCore.QSize(300, 40))
        self.selectCourseLabel_2.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.selectCourseLabel_2.setFont(font)
        self.selectCourseLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.selectCourseLabel_2.setObjectName("selectCourseLabel_2")
        self.verticalLayout_4.addWidget(self.selectCourseLabel_2)
        self.courseComboBox_2 = QtWidgets.QComboBox(self.studentInBatch)
        self.courseComboBox_2.setMinimumSize(QtCore.QSize(300, 40))
        self.courseComboBox_2.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.courseComboBox_2.setFont(font)
        self.courseComboBox_2.setObjectName("courseComboBox_2")
        self.courseComboBox_2.addItem("")
        self.verticalLayout_4.addWidget(self.courseComboBox_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.label_5 = QtWidgets.QLabel(self.studentInBatch)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.studentInBatch)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.selectBatchLabel_2 = QtWidgets.QLabel(self.studentInBatch)
        self.selectBatchLabel_2.setMinimumSize(QtCore.QSize(300, 40))
        self.selectBatchLabel_2.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.selectBatchLabel_2.setFont(font)
        self.selectBatchLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.selectBatchLabel_2.setObjectName("selectBatchLabel_2")
        self.verticalLayout_5.addWidget(self.selectBatchLabel_2)
        self.batchComboBox_2 = QtWidgets.QComboBox(self.studentInBatch)
        self.batchComboBox_2.setMinimumSize(QtCore.QSize(300, 40))
        self.batchComboBox_2.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.batchComboBox_2.setFont(font)
        self.batchComboBox_2.setObjectName("batchComboBox_2")
        self.verticalLayout_5.addWidget(self.batchComboBox_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.label_7 = QtWidgets.QLabel(self.studentInBatch)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.label_8 = QtWidgets.QLabel(self.studentInBatch)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.studentsInBatchTable = QtWidgets.QTableWidget(self.studentInBatch)
        self.studentsInBatchTable.setMinimumSize(QtCore.QSize(750, 0))
        self.studentsInBatchTable.setMaximumSize(QtCore.QSize(800, 16777215))
        self.studentsInBatchTable.setAlternatingRowColors(True)
        self.studentsInBatchTable.setObjectName("studentsInBatchTable")
        self.studentsInBatchTable.setColumnCount(3)
        self.studentsInBatchTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.studentsInBatchTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.studentsInBatchTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.studentsInBatchTable.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_9.addWidget(self.studentsInBatchTable)
        self.label_9 = QtWidgets.QLabel(self.studentInBatch)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.studentInBatch)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.backButton_2 = QtWidgets.QPushButton(self.studentInBatch)
        self.backButton_2.setMinimumSize(QtCore.QSize(150, 40))
        self.backButton_2.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backButton_2.setFont(font)
        self.backButton_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.backButton_2.setObjectName("backButton_2")
        self.horizontalLayout_10.addWidget(self.backButton_2)
        self.label_11 = QtWidgets.QLabel(self.studentInBatch)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 1, 1, 1)
        self.tabWidget.addTab(self.studentInBatch, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        SearchInBatch.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SearchInBatch)
        self.statusbar.setObjectName("statusbar")
        SearchInBatch.setStatusBar(self.statusbar)

        self.retranslateUi(SearchInBatch)
        self.tabWidget.setCurrentIndex(0)
        self.batchComboBox.hide()
        self.selectBatchLabel.hide()

        # Loading Courses in Combo Box for both tabs
        mycursor = mydb.cursor(buffered=True)
        mycursor.execute("SELECT course_name FROM courses_table")
        result = mycursor.fetchall()
        self.courseComboBox.clear()
        self.courseComboBox_2.clear()
        for x in result:
            self.courseComboBox.addItem(x[0])  # TAB1
            self.courseComboBox_2.addItem(x[0])  # TAB2

        # Setting Current index to -1 for courseComboBox
        self.courseComboBox.setCurrentIndex(-1)
        self.courseComboBox_2.setCurrentIndex(-1)

        # SIGNAL TO LOAD BATCHES
        self.courseComboBox.currentIndexChanged.connect(self.loadBatchesTab1)
        self.courseComboBox_2.currentIndexChanged.connect(self.loadBatchesTab2)

        # SIGNAL TO LOAD STUDENTS
        self.batchComboBox_2.currentIndexChanged.connect(self.loadStudents)

        QtCore.QMetaObject.connectSlotsByName(SearchInBatch)

    # FOR TAB1

    def loadBatchesTab1(self):
        mycursor = mydb.cursor(buffered=True)
        curCourseName = self.courseComboBox.currentText()
        sql = "SELECT course_id FROM courses_table WHERE course_name = '" + curCourseName + "'"
        mycursor.execute(sql)
        temp = mycursor.fetchone() # Fetch course_id
        self.curCourse = temp[0]
        sql = "SELECT batch_id, batch_name, start_date FROM batches_table WHERE course_id = " + str(self.curCourse)
        mycursor.execute(sql)
        temp = mycursor.fetchall() # Fetch all batches info
        row = 0
        self.batchTable.setRowCount(mycursor.rowcount)
        # Adding data to table widget
        for x in temp:
            sql = "SELECT count(*) FROM student_course_batch WHERE batch_id = " + str(x[0]) # count students in batch
            mycursor.execute(sql)
            temp1 = mycursor.fetchone()
            self.batchTable.setItem(row, 0, QtWidgets.QTableWidgetItem(str(x[0]))) # Id
            self.batchTable.setItem(row, 1, QtWidgets.QTableWidgetItem(str(x[1]))) # Name
            self.batchTable.setItem(row, 2, QtWidgets.QTableWidgetItem(str(x[2]))) # StartDate
            self.batchTable.setItem(row, 3, QtWidgets.QTableWidgetItem(str(temp1[0]))) # students count
            row += 1
        self.setTableSizeTab1()

    # Size the column width for the table
    def setTableSizeTab1(self):
        header = self.batchTable.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch)
        header.setSectionResizeMode(3, QtWidgets.QHeaderView.Stretch)

    # FOR TAB2

    # Load Batches for course in batchcombobox
    def loadBatchesTab2(self):
        self.batchComboBox_2.clear()
        mycursor = mydb.cursor(buffered=True)
        curCourseName = self.courseComboBox_2.currentText()
        sql = "SELECT course_id FROM courses_table WHERE course_name = '" + curCourseName + "'"
        mycursor.execute(sql)
        temp = mycursor.fetchone() # Fetch course_id
        self.curCourse = temp[0]
        sql = "SELECT batch_name FROM batches_table WHERE course_id = " + str(self.curCourse)
        mycursor.execute(sql)
        temp = mycursor.fetchall() # Fetch Batches for course
        for x in temp:
            self.batchComboBox_2.addItem(x[0])
        self.batchComboBox_2.setCurrentIndex(-1)
        mycursor.close()

    # Load Students in batch
    def loadStudents(self):
        curBatchName = self.batchComboBox_2.currentText()
        mycursor = mydb.cursor(buffered=True)
        sql = "SELECT st.student_id, st.first_name, st.middle_name, st.last_name, scb.global_cert, b.batch_id FROM " \
              "student_info_table st, batches_table b, student_course_batch scb WHERE st.student_id = scb.student_id " \
              "AND scb.batch_id = b.batch_id AND b.batch_name = '" + curBatchName + "'"
        mycursor.execute(sql)
        temp = mycursor.fetchall() # Fetch students in batch
        row = 0
        self.studentsInBatchTable.setRowCount(mycursor.rowcount)
        for x in temp:
            fullName = x[1] + " " + x[2] + " " + x[3]
            self.studentsInBatchTable.setItem(row, 0, QtWidgets.QTableWidgetItem(str(x[0])))  # Id
            self.studentsInBatchTable.setItem(row, 1, QtWidgets.QTableWidgetItem(fullName))  # Name
            self.studentsInBatchTable.setItem(row, 2, QtWidgets.QTableWidgetItem(str(x[4])))  # GlobalCert
            row += 1

    # Size the column width for the table
    def setTableSizeTab2(self):
        header = self.studentsInBatchTable.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch)




    def retranslateUi(self, SearchInBatch):
        _translate = QtCore.QCoreApplication.translate
        SearchInBatch.setWindowTitle(_translate("SearchInBatch", "MainWindow"))
        self.batchInfoLabel.setText(_translate("SearchInBatch", "BATCH INFO"))
        self.selectCourseLabel.setText(_translate("SearchInBatch", "Select Course"))
        self.selectBatchLabel.setText(_translate("SearchInBatch", "Select Batch"))
        item = self.batchTable.horizontalHeaderItem(0)
        item.setText(_translate("SearchInBatch", "Id"))
        item = self.batchTable.horizontalHeaderItem(1)
        item.setText(_translate("SearchInBatch", "Batch Name"))
        item = self.batchTable.horizontalHeaderItem(2)
        item.setText(_translate("SearchInBatch", "Date of Commencement"))
        item = self.batchTable.horizontalHeaderItem(3)
        item.setText(_translate("SearchInBatch", "Total Number of Students"))
        self.backButton.setText(_translate("SearchInBatch", "Back"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.batchInfo), _translate("SearchInBatch", "Batch Info"))
        self.studentInBatchLabel.setText(_translate("SearchInBatch", "STUDENTS IN BATCH"))
        self.selectCourseLabel_2.setText(_translate("SearchInBatch", "Select Course"))
        # self.courseComboBox_2.setItemText(0, _translate("SearchInBatch", "asd"))
        self.selectBatchLabel_2.setText(_translate("SearchInBatch", "Select Batch"))
        item = self.studentsInBatchTable.horizontalHeaderItem(0)
        item.setText(_translate("SearchInBatch", "Id"))
        item = self.studentsInBatchTable.horizontalHeaderItem(1)
        item.setText(_translate("SearchInBatch", "Student Name"))
        item = self.studentsInBatchTable.horizontalHeaderItem(2)
        item.setText(_translate("SearchInBatch", "Global Certification"))
        self.backButton_2.setText(_translate("SearchInBatch", "Back"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.studentInBatch),
                                  _translate("SearchInBatch", "Students in Batch"))
        self.setTableSizeTab1()
        self.setTableSizeTab2()
